backend/controllers/MainController.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 05.03.2018
 * Time: 13:57
 */

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use backend\models\SignupForm;
use common\models\LoginForm;
use yii\filters\AccessControl;

class MainController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?']
                    ]
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionSignup()
    {
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model
        ]);
    }
}

frontend/controllers/MainController.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 01.03.2018
 * Time: 0:48
 */

namespace frontend\controllers;


use backend\models\News;
use backend\models\Order;
use backend\models\ReturnTicket;
use backend\models\Schedule;
use yii\web\Controller;
use Yii;
use common\models\LoginForm;
use frontend\models\SignupForm;
use yii\data\ActiveDataProvider;
use backend\models\RouteStation;

class MainController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }
    public function actionSchedule()
    {
        $model = new Schedule();
        $query = Schedule::find();
        $sort = Yii::$app->request->get('sort');


        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        if ($sort == 1)
        {
            $query->joinWith(['route'])->orderBy(['number' => SORT_ASC]);
        }
        else if ($sort == 2)
        {
            $query->joinWith(['route'])->orderBy(['number' => SORT_DESC]);
        }
//        else if ($sort == 3)
//        {
////            $query->with('route')->viaTable(RouteStation::tableName(), ['id_route' => 'id'], function($q){
////                $q->distinct('id_route')->orderBy(['time' => SORT_ASC]);
////            });
//            $query->joinWith(['route.routeStations'])->orderBy(['arrival_time' => SORT_ASC]);
////            $query->joinWith(['routeStations'])->orderBy(['time' => SORT_ASC]);
//        }
//        else if ($sort == 4)
//        {
//            $query->joinWith(['route.routeStations'])->orderBy(['arrival_time' => SORT_DESC]);
//        }
//        else if ($sort == 5)
//        {
//            $query->joinWith(['route.routeStations'])->orderBy(['time' => SORT_ASC]);
////            $query->joinWith(['route.routeStations'=>function($query) {
////                return $query->distinct('id_route')->orderBy(['arrival_time' => SORT_ASC]);
////            }]);
//        }
//        else if ($sort == 6)
//        {
//            $query->joinWith(['route.routeStations'])->orderBy(['time' => SORT_DESC]);
//        }

        return $this->render('schedule', [
            'dataProvider' => $dataProvider,
            'model' => $model,
            'sort' => $sort
        ]);
    }
    public function actionReturn()
    {
        $model = new ReturnTicket();

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            $return_money='Ивините, время истекло';
            if($model->numberTicket->status==1){
                if($model->numberTicket->customer->phone_number==$model->phone || $model->numberTicket->orderProfiles->profile->phone_number==$model->phone){
    //               var_dump('phone');
                    if($model->numberTicket->create_at==$model->date_pay ){
    //                    var_dump('date');
                        if($model->numberTicket->customer->full_name==$model->full_name ||$model->numberTicket->orderProfiles->profile->second_name.' '.$model->numberTicket->orderProfiles->profile->first_name.' '.$model->numberTicket->orderProfiles->profile->third_name==$model->full_name){
    //                        var_dump('name');
                            if($model->numberTicket->status!=4){
    //                            var_dump('final');
                                $model->numberTicket->status=4;
                                $model->numberTicket->save();

                                $date=date('d.m.Y H:i:s');
                                $time='';
                                foreach ($model->numberTicket->schedule->route->routeStations as $station){
                                    if($model->numberTicket->station_departure==$station->station->title){
                                        $time=$station->time;
                                    }
                                }
                                $departure=$model->numberTicket->departure_date.' '.$time;
                                $d1=strtotime($departure);
                                $d2=strtotime($date);
                                $result=($d1-$d2)/60;
                                if($result>=10){
                                    $return_money=$model->numberTicket->end_price*0.8;
                                }
                                if($result>=120){
                                    $return_money=$model->numberTicket->end_price*0.9;
                                }
                                if($result>=1440){
                                    $return_money=$model->numberTicket->end_price;
                                }
                                if($result<0 && $result>=-60 || $result<10){
                                    $return_money=$model->numberTicket->end_price*0.7;
                                }
                            }
                        }
                    }
                }
            }
            else {$return_money='Ивините, вы еще не оплатили билет';}
//            die();
            return $this->redirect(['result', 'money'=>$return_money]);
        }

        return $this->render('return',[
            'model' => $model
        ]);
    }

    public function actionResult($money)
    {
        return $this->render('result',['money'=>$money]);
    }

    public function actionNews()
    {
        $query = News::find()->where(['status' => 1]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => ['defaultOrder'=>['id'=>'desc']]
        ]);

        return $this->render('news',[
            'dataProvider' => $dataProvider
        ]);
    }
    public function actionContacts()
    {
        return $this->render('contacts');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->redirect(['/profile/create']);
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/views/main/_data_news.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 10.04.2018
 * Time: 22:53
 */

/* @var $this \yii\web\view */
/* @var $model \backend\models\News */

?>
<div class='cbm_wrap '>
        <span class='horiz-flag noise '> <h1 id = "title-news"><?= $model->title ?></h1></span>
            <?php $images = $model->getImages() ?>
            <?php foreach ($images as $image): ?>
                <img src="<?= $image->getUrl(''); ?>" alt="">
            <?php endforeach; ?>
        <p>
            <?= $model->description ?>
        </p>

        <span class='horiz-flag1 noise1 '> <h4 id = 'date'><?= $model->created_at ?></h4></span>
    </div>

frontend/views/main/_data_schedule.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 29.03.2018
 * Time: 14:58
 */

use backend\models\RouteStation;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this \yii\web\view */
/* @var $model \backend\models\Schedule */
/* @var $form yii\widgets\ActiveForm*/

$routeStation = RouteStation::findAll(['id_route' => $model->id_route]);

?>

<div class="divTableRow">
    <div class="divTableCell" id="col-width-num">
        <?= $model->route->number ?>
    </div>
        <div class="divTableCell">
            <?= $model->route->title ?>
        </div>

        <div class="divTableCell">
            <?php if ($model->mode === 1): ?>
                по нечетным
            <?php elseif ($model->mode ===2): ?>
                по четным
            <?php else: ?>
                ежедневно
            <?php endif; ?>
        </div>
        <div class="divTableCell" id="col-center">
            <?php $lastStation=count($model->route->routeStations); ?>
            <?php for($i=0; $i<$lastStation; $i++):?>
                <?php if($i==$lastStation-1): ?>
                    <?= $model->route->routeStations[$i]['arrival_time'] ?>
                <?php endif; ?>
            <?php endfor; ?>
        </div>
        <div class="divTableCell" id="col-center">
            <?php foreach ($model->route->routeStations as $routeStation): ?>
                <?= $routeStation->time?>
                <?php break; ?>
            <?php endforeach; ?>
        </div>
        <div class="divTableCell">
<!--            --><?//= Html::a('Подробнее',['/schedule/detail','id' => $model->id],['class' => 'btn btn-details']) ?>
            <div>
                   <?php
                    Modal::begin([
                        'header' =>'<h3>'.$model->route->title.'</h3>',
                        'toggleButton' => [
                            'label' => 'Подробнее',
                            'tag' => 'button',
                            'class' => 'btn btn-details',],
                        'options'=>['class'=> 'modal-detail']
                    ]);
                   ?>
                <div class="divSmallTable sch-small-table">
                    <div class="divSmallTableHeading">
                        <div class="divSmallTableHead">Станции</div>
                        <div class="divSmallTableHead">Время прибытия</div>
                        <div class="divSmallTableHead">Время отправления</div>
                    </div>

                        <div class="divSmallTableBody">
                            <?php foreach ($model->route->routeStations as $rs): ?>

                               <div class="divSmallTableRow">

                                   <div class="divSmallTableCell"> <?= Html::input('checkbox', 'departure', $rs->station->title,['class'=>'limit_checkbox', 'id'=>'checkbox1', 'data-id'=>$model->id])?>

                                       <?= $rs->station->title ?></div>
                                   <div class="divSmallTableCell"><?= $rs->arrival_time?></div>
                                   <div class="divSmallTableCell"><?= $rs->time ?></div>
                               </div>
                            <?php endforeach; ?>
                            <?= DatePicker::widget([
                                'id' => 'date'.$model->id,
                                'name' => 'departure_date',
                                'language' => 'ru',
                                'value' => date('d.m.Y'),
                                'options' => [
                                        'class' => 'date-picker-schedule'
                                ],
                                'pluginOptions' => [
                                        'startDate' => date('d.m.Y')
                                ],
                            ]); ?>
                        </div>
                </div>

                <div>
                    <?= Html::a('Купить билет',['/schedule/schedule-view','id' => $model->id_route],['class' => 'btn btn-save', 'id' => 'btn-buy'.$model->id, 'data-id' => $model->id]) ?>
                </div>
                <?php Modal::end(); ?>
            </div>
        </div>

</div>

frontend/views/main/contacts.php
<?php

use yii\widgets\ListView;
use voime\GoogleMaps\Map;

/* @var $this \yii\web\view */

$this->title = 'Контакты';

//$this->registerJsFile('https://maps.googleapis.com/maps/api/js?key=AIzaSyC-fcAKfCosG70KPap6ZA1en0iurBEylTk&callback=initMap', ['depends' => [yii\web\JqueryAsset::className()]])

?>
<div class="contacts-block">
    <table class="table_info">
        <caption>Контактная информация</caption>
        <tr>
            <td>Адрес</td>
            <td>г.Киев, ул.Дорожницкого,17</td>
        </tr>
        <tr>
            <td>Телефон</td>
            <td>(044)220-55-32</td>
        </tr>
        <tr>
            <td>Мобильный</td>
           <td>095-153-03-33
        <p>096-712-00-41</p></td>
        </tr>
        <tr>
            <td>E-mail</td>
            <td>busstation@gmail.com</td>
        </tr>
    </table>
</div>

<div class="contacts-block">
    <table class="table_info">
        <caption>График работы</caption>
        <tr>
            <td>Офис в Киеве</td>
            <td>Пн-Пт с 9:00 до 17:00</td>
        </tr>
    </table>
</div>


<div class="contacts-block">
    <table class="table_info">
        <caption>Наше расположение</caption>
    </table>
    <?php echo Map::widget([
        'apiKey'=> 'AIzaSyC-fcAKfCosG70KPap6ZA1en0iurBEylTk',
        'zoom' => 16,
        'center' => [50.469901, 30.443973],
        'width' => '80%',
        'height' => '600px',
        'markers' => [
        ['position' => [50.469901,30.443973]]],
        'mapType' => Map::MAP_TYPE_ROADMAP,
    ]); ?>
</div>

frontend/views/main/index.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 01.03.2018
 * Time: 0:49
 */

use yii\helpers\Url;
use yii\jui\AutoComplete;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use kartik\date\DatePicker;
use yii\bootstrap\Carousel;

/* @var $this \yii\web\view */
/* @var $model \backend\models\Schedule */
$this->title = 'Главная';

?>

<div class="string">
    <div id="marquee">

    </div>
</div>

<div class="carouselmain">
    <?php
    echo Carousel::widget([
        'items' => [
            // the item contains only the image
         ['content' =>  Html::img('@web/image/bustourist.jpg',  ['class'=>'img-carousel']),
           'caption' => '<div class="slideUp">
				<ul id="slide-text" class="back-text">
                    <h1>Путешествуй вместе с нами</h1>
					<li>более 300 направлений</li>
					<li>комфортные автобусы</li>
					<li>круглосуточная служба поддержки</li>
				</ul>
				</div>'
         ],
        // equivalent to the above
            [
                 'content' => Html::img('@web/image/oportunity.jpg',  ['class'=>'img-carousel']),
                 'caption' => '<div class="slideUp">
				 <ul id="slide-text" class="back-text">
                    <h1>Актуальные возможности</h1>
					<li>покупка билетов</li>
					<li>возврат билетов</li>
					<li>оповещения о рейсовых изменениях</li>
				</ul>
				</div>',
            ],
            // the item contains both the image and the caption

            [
                'content' => Html::img('@web/image/oplata.jpg',  ['class'=>'img-carousel']),
                'caption' => '<div class="slideUp">
				<ul id="slide-text" class="back-text">
                    <h1>Универсальная оплата</h1>
					<li>платежные карты</li>
					<li>элеткронные деньги</li>
					<li>Приват24</li>
				</ul>
				</div>',
            ],
//            [
//                'content' => Html::img('@web/image/insidepng.png',  ['class'=>'img-carousel'])
//                // 'caption' => '<h4>This is title</h4><p>This is the caption text</p>',
//            ],
        ],
        'options' => ['class' => 'carousel slide', 'data-interval' => '5000'],
        'controls' => [
            '<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>',
            '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>'
        ]
    ]);
    ?>
</div>

<div class="titul-form">
    <h3>Поиск билетов на автобус</h3>
</div>


<?php $form = ActiveForm::begin([
    'action' => ['schedule/search'],
]); ?>
<div class="autocomplete-block">

   <div class="autocomplete-general">
        <div class="autocomplete-input1">
        <span id="text-form">Откуда</span>
    <?= AutoComplete::widget([
//    'model' => 'title',
//    'attribute' => 'title',
        'name' => 'departure',
        'id' => '1',
        'options' => ['class' => 'form-control'],
        'clientOptions' => [
            'source' => Url::to(['schedule/route']),
            'minLength'=>'1',
            'limit' => '1'
        ],
    ]); ?>
        </div>
       <div class="autocomplete-general">
       <div class="autocomplete-transfer">
            <span class="glyphicon glyphicon-transfer"></span>
       </div>
       </div>
        <div class="autocomplete-input2">
        <span id="text-form">Куда</span>
        <?= AutoComplete::widget([
//    'model' => $model,
            'name' => 'arrival',
            'id' => '2',
            'attribute' => 'title',
            'options' => ['class' => 'form-control'],
            'clientOptions' => [
                'source' => Url::to(['schedule/routet']),
                'minLength'=>'1',
            ],
        ]); ?>
        </div>
   </div>
    <div class="autocomplete-general">
     <div class="autocomplete-input3">
         <span id="text-form">Дата</span>
        <?= DatePicker::widget([
            'name' => 'departure_date',
            'language' => 'ru',
            'value' => date('d.m.Y'),
            'pluginOptions' => [
                'startDate' => date('d.m.Y')
            ]
        ]); ?>
    </div>
    <div class="form-group-btn">
        <?= Html::submitButton('Найти', ['class' => 'btn btn-save']) ?>
    </div>
</div>
</div>
<?php ActiveForm::end(); ?>


<div class="container clearfix">
    <div class="block-buy">
        <h3>Покупка онлайн</h3>
        <div class="block2-buy">
            <div class="image-info">
                    <?= Html::img('@web/image/infobus.jpg') ?>
             </div>
            <div class="text-info">
        Нужно купить автобусные билеты? Busstation.ua без проблем поможет в поиске билета. На сайте Вы найдете расписание автобусов по Украине, также узнаете есть ли свободные места и стоимость билетов, забыв об очередях в автобусную кассу. На Busstation.ua купить билеты легко и просто: необходимо выбрать нужное автобусное направление и указать дату в календаре. Система выдаст подходящие варианты автобусных рейсов по Вашему запросу. Далее выбираете самый удобный и дешевый вариант и покупаете билет на сайте. Busstation.ua сэкономит Ваше время и поможет приобрести билеты на автобус по выгодной цене.
        </div>
        </div>
    </div>
    <div class="block-return">
    <h3>Возврат онлайн</h3>
    <div class="block2-return">
        <div class="image-info">
            <?= Html::img('@web/image/returnTick.jpg') ?>
        </div>
        <div class="text-info">
        На сайте Busstation.ua не только легко купить билет на автобус онлайн, но и легко его вернуть. Возврат билета осуществляется согласно государственному постановлению КМУ «Правила предоставления услуг пассажирского автомобильного транспорта».
        Вернуть неиспользованные автобусные билеты вы можете, заполнив форму "Возврат билета".
        Средства за неиспользованный билет вернутся вам в течение 30 дней. Условия возврата денежных средств варьируются в зависимости от времени до и после отправления автобуса.
    </div>
    </div>
    </div>
</div>

frontend/views/main/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Авторизация';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-login">
    <div class="login-form">
        <div class="login-form-in">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните необходимые поля, чтобы войти в систему:</p>

    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    Если забыли пароль,то можно <?= Html::a('возобновить', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                    <?= Html::a('Регистрация', ['/main/signup'], ['class' => 'btn btn-info']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
</div>
</div>

frontend/views/main/news.php
<?php

use yii\widgets\ListView;
use yii\helpers\Html;

/* @var $this \yii\web\view */
/* @var $model \backend\models\News */

$this->title = 'Новости';
?>

​<div class='wrapper_body'>
    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'summary' => '',
        'itemOptions' => ['class' => 'item'],
        'itemView' => function ($model) {
            return $this->render('_data_news',[
                'model' => $model
            ]);
        },
    ]) ?>
</div>

frontend/views/main/result.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 02.04.2018
 * Time: 14:46
 */
?>

<?= $money ?>

frontend/views/main/return.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model backend\models\ReturnTicket */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Возврат билета';

?>

<div class="wrapper">
    <div class="row">
        <div class="col-2-3">
            <h3>Правила возврата автобусных билетов:</h3>
            <table class ="return-table">
                        <tr>
                            <th>Время оставшееся до отправления автобуса</th>
                            <th>Удержания*</th>
                            <th>Возврат*</th>
                        </tr>
                        <tr>
                            <td>Более 24 часов до отправления</td>
                            <td>0%*</td>
                            <td>100%</td>
                        </tr>
                        <tr>
                            <td>2 часа до момента отправления</td>
                            <td>10%</td>
                            <td>90%</td>
                        </tr>
                        <tr>
                            <td>10 минут до отправления автобуса</td>
                            <td>20%</td>
                            <td>80%</td>
                        </tr>
                        <tr>
                            <td>менее 10 минут, но более трех часов после отправления</td>
                            <td>30%</td>
                            <td>70%</td>
                        </tr>
                    </table>
        </div>
        <div class="col-1-3">
            <p>*В таблице указаны только проценты от стоимости билета. Комиссионные сборы системы Uticket и платежных систем не возвращается.</p>
                <p>*Согласно http://zakon3.rada.gov.ua/laws/show/176-97-%D0%BF  ст.136
                    -Пассажир имеет право на возврат билета в течение трех суток с момента отправления автобуса в случае болезни или несчастного случая, что подтверждается соответствующими документами.
                    В таком случае ему возмещается уплаченная сумма, кроме платы за продажу билетов, или бесплатно переоформляется билет на другой автобус.
                    Если человек заболел и не в состоянии самостоятельно вернуть билет в кассу автостанции, то в таких случаях необходимо действовать, не теряя времени, через третьих лиц.
                </p>
        </div>
    </div><!-- /.row -->

    <div class="row">
        <div class="return-text">
            Если пассажир по каким-либо причинам не может воспользоваться
            своим автобусным билетом и намерен сдать его и вернуть часть стоимости билета,
            в зависимости от того, какой из видов билетов был приобретен, необходимо заполнить cоответствующую форму.
        </div>
        <div class="col-1-4">
        </div>
        <div class="col-2-4">
            <div class="return-ticket-form">
                <div class="return-form-in">
                    <?php $form = ActiveForm::begin(); ?>

                    <?= $form->field($model, 'number_ticket')->textInput() ?>

                    <?= $form->field($model, 'full_name')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'number_card')->textInput() ?>

                    <?= $form->field($model, 'phone')->textInput() ?>

                    <?= $form->field($model, 'date_pay')->widget(DatePicker::classname(),
//        [
//        'type' => DatePicker::TYPE_INLINE,
//        'options' => ['placeholder' => 'Введите дату оплаты ...'],
//        'language' => 'ru',
//        'pluginOptions' => [
////            'autoclose'=>true
//        ]
                        [
                            'type' => DatePicker::TYPE_COMPONENT_PREPEND,
                            'language' => 'ru',
                            'value' => date('d/m/y'),
                            'pluginOptions' => [
                                'autoclose'=>true,
//                'format' => 'd/m/yy'
                            ]
                        ]); ?>
                <div class="row">
                    <div class="col-1-5"></div>
                    <div class="col-4-5">
                        <?= Html::submitButton('Вернуть билет', ['class' => 'btn btn-return']) ?>
                    </div>
                </div>
                    <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
        <div class="col-1-4">
        </div>
</div><!-- /.row -->
</div>

frontend/views/main/schedule.php
<?php

use yii\widgets\ListView;
use yii\helpers\Html;
use yii\widgets\Pjax;

/* @var $this \yii\web\view */
/* @var $model \backend\models\Schedule */
/* @var $sort int */

$this->title = 'Расписание';
?>
<?php Pjax::begin()?>

<div class="divTable sch-table">
    <div class="divTableHeading">
        <div class="divTableRowHead">
            <div class="divTableHead" id="col-width-num1">
                №
                <?php if ($sort == null || $sort == 2 || $sort == 3 || $sort == 4 || $sort == 5 || $sort == 6): ?>
                    <?= Html::a('<span class="glyphicon glyphicon-chevron-up"></span>', ['/main/schedule', 'sort' => 1], ['class' => 'sort-number-asc','data-pjax' => true]); ?>
                <?php elseif ($sort == 1): ?>
                    <?= Html::a('<span class="glyphicon glyphicon-chevron-down"></span>', ['/main/schedule', 'sort' => 2], ['class' => 'sort-number-desc','data-pjax' => true]); ?>
                <?php endif; ?>
            </div>
            <div class="divTableHead">Рейс</div>

<!--            <div class="divTableHead">Маршрут</div>-->
            <div class="divTableHead" >График</div>
            <div class="divTableHead" id="col-center">
                Время отправления
                <?php if ($sort == null || $sort == 1 || $sort == 2 || $sort == 4 || $sort == 5 || $sort == 6): ?>
                    <?= Html::a('<span class="glyphicon glyphicon-chevron-up"></span>', ['/main/schedule', 'sort' => 3], ['class' => 'sort-number-asc','data-pjax' => true]); ?>
                <?php elseif ($sort == 3): ?>
                    <?= Html::a('<span class="glyphicon glyphicon-chevron-down"></span>', ['/main/schedule', 'sort' => 4], ['class' => 'sort-number-desc','data-pjax' => true]); ?>
                <?php endif; ?>
            </div>
            <div class="divTableHead" id="col-center">
                Время прибытия
                <?php if ($sort == null || $sort == 1 || $sort == 2 || $sort == 3 || $sort == 4 || $sort == 6): ?>
                    <?= Html::a('<span class="glyphicon glyphicon-chevron-up"></span>', ['/main/schedule', 'sort' => 5], ['class' => 'sort-number-asc','data-pjax' => true]); ?>
                <?php elseif ($sort == 5): ?>
                    <?= Html::a('<span class="glyphicon glyphicon-chevron-down"></span>', ['/main/schedule', 'sort' => 6], ['class' => 'sort-number-desc','data-pjax' => true]); ?>
                <?php endif; ?>
            </div>
            <div class="divTableHead" > </div>
        </div>
    </div>
    <div class="divTableBody">
        <?= ListView::widget([
                'dataProvider' => $dataProvider,
//                'sorter' => ['attributes'=>'number'],
                'summary' => '',
                'options' => [
                    'data-pjax' => true
                ],
                'itemOptions' => [
                    'class' => 'item',
                ],
                'itemView' => function ($model) {
                    return $this->render('_data_schedule',[
                        'model' => $model
                    ]);
                },
            ]) ?>
    </div>
</div>

<?php Pjax::end(); ?>